-- =====================================================================
-- Migration 077: RU proxy role and selective egress policy
-- =====================================================================

SET @col_exists := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'vpn_servers' AND COLUMN_NAME = 'role'
);
SET @sql := IF(@col_exists = 0,
  "ALTER TABLE vpn_servers ADD COLUMN role ENUM('vpn','ru_proxy') NOT NULL DEFAULT 'vpn' AFTER user_id, ADD INDEX idx_role (role)",
  "SELECT 1"
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

CREATE TABLE IF NOT EXISTS ru_proxy_configs (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  server_id INT UNSIGNED NOT NULL UNIQUE,
  transport ENUM('wireguard','awg2') NOT NULL DEFAULT 'wireguard',
  listen_port INT UNSIGNED NULL,
  tunnel_subnet VARCHAR(50) NOT NULL DEFAULT '10.250.0.0/16',
  public_key TEXT NULL,
  endpoint VARCHAR(255) NULL,
  status ENUM('active','inactive','error') NOT NULL DEFAULT 'inactive',
  last_applied_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_transport (transport),
  INDEX idx_status (status),
  FOREIGN KEY (server_id) REFERENCES vpn_servers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS egress_route_policies (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  server_id INT UNSIGNED NOT NULL,
  proxy_server_id INT UNSIGNED NULL,
  transport ENUM('wireguard','awg2') NOT NULL DEFAULT 'wireguard',
  enabled TINYINT(1) NOT NULL DEFAULT 0,
  fallback_mode ENUM('warp','direct','block') NOT NULL DEFAULT 'warp',
  last_applied_at TIMESTAMP NULL,
  last_error TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_server_policy (server_id),
  INDEX idx_proxy_server (proxy_server_id),
  FOREIGN KEY (server_id) REFERENCES vpn_servers(id) ON DELETE CASCADE,
  FOREIGN KEY (proxy_server_id) REFERENCES vpn_servers(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS egress_route_rules (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  policy_id INT UNSIGNED NOT NULL,
  type ENUM('ip','cidr','domain') NOT NULL,
  value VARCHAR(255) NOT NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  comment VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_policy_value (policy_id, type, value),
  INDEX idx_policy_enabled (policy_id, enabled),
  FOREIGN KEY (policy_id) REFERENCES egress_route_policies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS egress_route_resolved_ips (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  rule_id INT UNSIGNED NOT NULL,
  ip VARCHAR(45) NOT NULL,
  last_resolved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_rule_ip (rule_id, ip),
  FOREIGN KEY (rule_id) REFERENCES egress_route_rules(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO protocols (name, slug, description, install_script, uninstall_script, output_template, ubuntu_compatible, is_active, show_text_content, definition, created_at, updated_at)
VALUES (
  'RU Proxy WireGuard',
  'ru-proxy',
  'WireGuard relay server for selective RU egress. Used as a server-to-server transport for selected IPs and domains.',
  FROM_BASE64('IyEvYmluL2Jhc2gKc2V0IC1ldW8gcGlwZWZhaWwKCklGQUNFPSIke1JVX1BST1hZX0lGQUNFOi1ydS1wcm94eTB9IgpQT1JUPSIke1JVX1BST1hZX1BPUlQ6LTQzMTAwfSIKU1VCTkVUPSIke1JVX1BST1hZX1NVQk5FVDotMTAuMjUwLjAuMC8xNn0iClNUQVRFX0RJUj0iL3Zhci9saWIvYW1uZXppYS1ydS1wcm94eSIKQ09ORj0iL2V0Yy93aXJlZ3VhcmQvJHtJRkFDRX0uY29uZiIKRVhUX0lGPSIkKGlwIHJvdXRlIHNob3cgZGVmYXVsdCAyPi9kZXYvbnVsbCB8IGF3ayAne3ByaW50ICQ1OyBleGl0fScpIgpbIC1uICIkRVhUX0lGIiBdIHx8IEVYVF9JRj0iZXRoMCIKCmV4cG9ydCBERUJJQU5fRlJPTlRFTkQ9bm9uaW50ZXJhY3RpdmUKYXB0LWdldCB1cGRhdGUgLXFxCmFwdC1nZXQgaW5zdGFsbCAteSAtcXEgd2lyZWd1YXJkLXRvb2xzIGlwdGFibGVzIGlwcm91dGUyIGNhLWNlcnRpZmljYXRlcyA+L2Rldi9udWxsIDI+JjEKbWtkaXIgLXAgIiRTVEFURV9ESVIiIC9ldGMvd2lyZWd1YXJkCmNobW9kIDcwMCAiJFNUQVRFX0RJUiIKCmlmIFsgISAtcyAiJFNUQVRFX0RJUi9wcml2YXRla2V5IiBdOyB0aGVuCiAgd2cgZ2Vua2V5ID4gIiRTVEFURV9ESVIvcHJpdmF0ZWtleSIKICBjaG1vZCA2MDAgIiRTVEFURV9ESVIvcHJpdmF0ZWtleSIKZmkKd2cgcHVia2V5IDwgIiRTVEFURV9ESVIvcHJpdmF0ZWtleSIgPiAiJFNUQVRFX0RJUi9wdWJsaWNrZXkiClBSSVZBVEVfS0VZPSIkKGNhdCAiJFNUQVRFX0RJUi9wcml2YXRla2V5IikiClBVQkxJQ19LRVk9IiQoY2F0ICIkU1RBVEVfRElSL3B1YmxpY2tleSIpIgoKY2F0ID4gIiRDT05GIiA8PEVPRgpbSW50ZXJmYWNlXQpBZGRyZXNzID0gMTAuMjUwLjAuMS8xNgpMaXN0ZW5Qb3J0ID0gJFBPUlQKUHJpdmF0ZUtleSA9ICRQUklWQVRFX0tFWQpTYXZlQ29uZmlnID0gZmFsc2UKRU9GCmNobW9kIDYwMCAiJENPTkYiCgpjYXQgPiAvdXNyL2xvY2FsL3NiaW4vYW1uZXppYS1ydS1wcm94eS1hcHBseSA8PCdBUFBMWScKIyEvYmluL2Jhc2gKc2V0IC1ldW8gcGlwZWZhaWwKSUZBQ0U9IiR7UlVfUFJPWFlfSUZBQ0U6LXJ1LXByb3h5MH0iClBPUlQ9IiR7UlVfUFJPWFlfUE9SVDotNDMxMDB9IgpTVEFURV9ESVI9Ii92YXIvbGliL2FtbmV6aWEtcnUtcHJveHkiCkNPTkY9Ii9ldGMvd2lyZWd1YXJkLyR7SUZBQ0V9LmNvbmYiCkVYVF9JRj0iJChpcCByb3V0ZSBzaG93IGRlZmF1bHQgMj4vZGV2L251bGwgfCBhd2sgJ3twcmludCAkNTsgZXhpdH0nKSIKWyAtbiAiJEVYVF9JRiIgXSB8fCBFWFRfSUY9ImV0aDAiCnN5c2N0bCAtdyBuZXQuaXB2NC5pcF9mb3J3YXJkPTEgPi9kZXYvbnVsbApta2RpciAtcCAvZXRjL3N5c2N0bC5kCnByaW50ZiAnbmV0LmlwdjQuaXBfZm9yd2FyZD0xXG4nID4gL2V0Yy9zeXNjdGwuZC85OC1hbW5lemlhLXJ1LXByb3h5LmNvbmYKd2ctcXVpY2sgZG93biAiJElGQUNFIiA+L2Rldi9udWxsIDI+JjEgfHwgdHJ1ZQp3Zy1xdWljayB1cCAiJElGQUNFIgppcHRhYmxlcyAtQyBGT1JXQVJEIC1pICIkSUZBQ0UiIC1vICIkRVhUX0lGIiAtaiBBQ0NFUFQgMj4vZGV2L251bGwgfHwgaXB0YWJsZXMgLUkgRk9SV0FSRCAxIC1pICIkSUZBQ0UiIC1vICIkRVhUX0lGIiAtaiBBQ0NFUFQKaXB0YWJsZXMgLUMgRk9SV0FSRCAtaSAiJEVYVF9JRiIgLW8gIiRJRkFDRSIgLW0gY29ubnRyYWNrIC0tY3RzdGF0ZSBSRUxBVEVELEVTVEFCTElTSEVEIC1qIEFDQ0VQVCAyPi9kZXYvbnVsbCB8fCBpcHRhYmxlcyAtSSBGT1JXQVJEIDEgLWkgIiRFWFRfSUYiIC1vICIkSUZBQ0UiIC1tIGNvbm50cmFjayAtLWN0c3RhdGUgUkVMQVRFRCxFU1RBQkxJU0hFRCAtaiBBQ0NFUFQKaXB0YWJsZXMgLXQgbmF0IC1DIFBPU1RST1VUSU5HIC1zIDEwLjI1MC4wLjAvMTYgLW8gIiRFWFRfSUYiIC1qIE1BU1FVRVJBREUgMj4vZGV2L251bGwgfHwgaXB0YWJsZXMgLXQgbmF0IC1BIFBPU1RST1VUSU5HIC1zIDEwLjI1MC4wLjAvMTYgLW8gIiRFWFRfSUYiIC1qIE1BU1FVRVJBREUKQVBQTFkKY2htb2QgK3ggL3Vzci9sb2NhbC9zYmluL2FtbmV6aWEtcnUtcHJveHktYXBwbHkKCmNhdCA+IC9ldGMvc3lzdGVtZC9zeXN0ZW0vYW1uZXppYS1ydS1wcm94eS5zZXJ2aWNlIDw8RU9GCltVbml0XQpEZXNjcmlwdGlvbj1BbW5lemlhIFJVIHByb3h5IFdpcmVHdWFyZCByZWxheQpBZnRlcj1uZXR3b3JrLW9ubGluZS50YXJnZXQKV2FudHM9bmV0d29yay1vbmxpbmUudGFyZ2V0CgpbU2VydmljZV0KVHlwZT1vbmVzaG90ClJlbWFpbkFmdGVyRXhpdD15ZXMKRXhlY1N0YXJ0PS91c3IvbG9jYWwvc2Jpbi9hbW5lemlhLXJ1LXByb3h5LWFwcGx5CkV4ZWNTdG9wPS91c3IvYmluL3dnLXF1aWNrIGRvd24gJElGQUNFCgpbSW5zdGFsbF0KV2FudGVkQnk9bXVsdGktdXNlci50YXJnZXQKRU9GCgpzeXN0ZW1jdGwgZGFlbW9uLXJlbG9hZApzeXN0ZW1jdGwgZW5hYmxlIC0tbm93IGFtbmV6aWEtcnUtcHJveHkuc2VydmljZSA+L2Rldi9udWxsIDI+JjEKCkhPU1RfSVA9IiQoY3VybCAtNCAtcyAtLW1heC10aW1lIDggaWZjb25maWcubWUgMj4vZGV2L251bGwgfHwgaG9zdG5hbWUgLUkgfCBhd2sgJ3twcmludCAkMX0nKSIKZWNobyAiVmFyaWFibGU6IHJ1X3Byb3h5X3RyYW5zcG9ydD13aXJlZ3VhcmQiCmVjaG8gIlZhcmlhYmxlOiBydV9wcm94eV9pZmFjZT0kSUZBQ0UiCmVjaG8gIlZhcmlhYmxlOiBydV9wcm94eV9wb3J0PSRQT1JUIgplY2hvICJWYXJpYWJsZTogcnVfcHJveHlfc3VibmV0PSRTVUJORVQiCmVjaG8gIlZhcmlhYmxlOiBydV9wcm94eV9wdWJsaWNfa2V5PSRQVUJMSUNfS0VZIgplY2hvICJWYXJpYWJsZTogcnVfcHJveHlfZW5kcG9pbnQ9JEhPU1RfSVA6JFBPUlQiCmVjaG8gIlZhcmlhYmxlOiBydV9wcm94eV9zdGF0dXM9YWN0aXZlIg=='),
  FROM_BASE64('IyEvYmluL2Jhc2gKc2V0IC1ldW8gcGlwZWZhaWwKSUZBQ0U9IiR7UlVfUFJPWFlfSUZBQ0U6LXJ1LXByb3h5MH0iCkVYVF9JRj0iJChpcCByb3V0ZSBzaG93IGRlZmF1bHQgMj4vZGV2L251bGwgfCBhd2sgJ3twcmludCAkNTsgZXhpdH0nKSIKWyAtbiAiJEVYVF9JRiIgXSB8fCBFWFRfSUY9ImV0aDAiCnN5c3RlbWN0bCBkaXNhYmxlIC0tbm93IGFtbmV6aWEtcnUtcHJveHkuc2VydmljZSAyPi9kZXYvbnVsbCB8fCB0cnVlCndnLXF1aWNrIGRvd24gIiRJRkFDRSIgPi9kZXYvbnVsbCAyPiYxIHx8IHRydWUKd2hpbGUgaXB0YWJsZXMgLUQgRk9SV0FSRCAtaSAiJElGQUNFIiAtbyAiJEVYVF9JRiIgLWogQUNDRVBUIDI+L2Rldi9udWxsOyBkbyA6OyBkb25lCndoaWxlIGlwdGFibGVzIC1EIEZPUldBUkQgLWkgIiRFWFRfSUYiIC1vICIkSUZBQ0UiIC1tIGNvbm50cmFjayAtLWN0c3RhdGUgUkVMQVRFRCxFU1RBQkxJU0hFRCAtaiBBQ0NFUFQgMj4vZGV2L251bGw7IGRvIDo7IGRvbmUKd2hpbGUgaXB0YWJsZXMgLXQgbmF0IC1EIFBPU1RST1VUSU5HIC1zIDEwLjI1MC4wLjAvMTYgLW8gIiRFWFRfSUYiIC1qIE1BU1FVRVJBREUgMj4vZGV2L251bGw7IGRvIDo7IGRvbmUKcm0gLWYgL2V0Yy9zeXN0ZW1kL3N5c3RlbS9hbW5lemlhLXJ1LXByb3h5LnNlcnZpY2UgL3Vzci9sb2NhbC9zYmluL2FtbmV6aWEtcnUtcHJveHktYXBwbHkgL2V0Yy93aXJlZ3VhcmQvJHtJRkFDRX0uY29uZiAvZXRjL3N5c2N0bC5kLzk4LWFtbmV6aWEtcnUtcHJveHkuY29uZgpybSAtcmYgL3Zhci9saWIvYW1uZXppYS1ydS1wcm94eQpzeXN0ZW1jdGwgZGFlbW9uLXJlbG9hZCAyPi9kZXYvbnVsbCB8fCB0cnVlCmVjaG8gJ3sic3VjY2VzcyI6dHJ1ZSwibWVzc2FnZSI6IlJVIHByb3h5IHJlbW92ZWQifSc='),
  FROM_BASE64('UlUgUHJveHkgV2lyZUd1YXJkIHJlbGF5ClRyYW5zcG9ydDoge3tydV9wcm94eV90cmFuc3BvcnR9fQpJbnRlcmZhY2U6IHt7cnVfcHJveHlfaWZhY2V9fQpFbmRwb2ludDoge3tydV9wcm94eV9lbmRwb2ludH19ClBvcnQ6IHt7cnVfcHJveHlfcG9ydH19ClB1YmxpYyBrZXk6IHt7cnVfcHJveHlfcHVibGljX2tleX19ClN0YXR1czoge3tydV9wcm94eV9zdGF0dXN9fQ=='),
  1,
  1,
  1,
  JSON_OBJECT(
    'engine', 'shell',
    'metadata', JSON_OBJECT(
      'server_role', 'ru_proxy',
      'requires_docker', false,
      'transport', 'wireguard',
      'container_name', 'ru-proxy',
      'listen_port', 43100,
      'tunnel_subnet', '10.250.0.0/16'
    ),
    'defaults', JSON_OBJECT(
      'role', 'ru_proxy',
      'transport', 'wireguard'
    )
  ),
  NOW(),
  NOW()
)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  description = VALUES(description),
  install_script = VALUES(install_script),
  uninstall_script = VALUES(uninstall_script),
  output_template = VALUES(output_template),
  ubuntu_compatible = VALUES(ubuntu_compatible),
  is_active = VALUES(is_active),
  show_text_content = VALUES(show_text_content),
  definition = VALUES(definition),
  updated_at = NOW();
